# Tomcat
server:
  port: 8080

spring:
  # 环境 dev|test|pro
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 127.0.0.1
    port: 6379
    password:       # 密码（默认为空）
  servlet:
    multipart:
      maxFileSize: 104857600 #100MB
      maxRequestSize: 104857600 #100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #解决swaggerUI不匹配接口

swagger:
  enable: true
  title: 德坤抖音后台 API
  description: API 描述
  version: 5.0.0
  author: ywj

# autofull 配置
autofull:
  showLog: false
  maxLevel: 1
  currLevel: 0
  encryptFlag: "@autofull@"
  encryptKeys: "abcdefg123456789"

#七牛 AK  和  SK可以去密钥管理中查询
qiniu:
  accessKey: 2222
  secretKey: 33333
  bucketName: qh-file
  domain: https://www.qiniu.com
  prefix: task

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true

staticResourceUrl: /static-resources/
staticResourcePath: C:/static/

douyin:
  appid: tt09537fee9664a91601
  secret: 52009ecc4abf90dc1e1ef48633dc2ba2fc82471a

wx:
  appkey: d92fb2cc9436f22b
  apipassword: 78b13253001ca367
  url:
    verifyOrLogin: https://openapi.dekuncn.com/gateway/dekun-plus-third/uat/dekun-boot/toktik/verifyOrLogin
    checkCoupon: https://openapi.dekuncn.com/gateway/dekun-plus-third/uat/dekun-boot/toktik/checkCoupon
    buyCoupon: https://openapi.dekuncn.com/gateway/dekun-plus-third/uat/dekun-boot/toktik/buyCoupon
    getAdvByPosition: https://openapi.dekuncn.com/gateway/dekun-plus-third/uat/dekun-boot/toktik/getAdvByPosition